spring:
  application:
    name: oauthJwt

  security:
    user:
      password: Admin@123
      name: admin

  datasource:
    url: jdbc:postgresql://localhost:5432/user-auth-service
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

app:
  jwt:
    secret: "xE7hKn6GVU8y1lXRA5nYqHfw8EhH7kB14DnZL1mxMfKqj3U3EYnYzF3ZjqMEJgh2"
    expiration-ms: 3600000